package com.gigssandbox;

public enum Response {
    REGISTRATION_SUCCESS,
    LOG_IN_SUCCESS,
    JOIN_COMMUNITY_SUCCESS,
    LEAVE_COMMUNITY_SUCCESS,
    HELP,
    LOG_OUT_SUCCESS,
    NOT_ENOUGH_PARAMETERS,
    UNSUPPORTED,
    NOT_REGISTERED,
    INCORRECT_PASSWORD
}
